### ISSUE TITLE
method #2

### ISSUE THREAD

**Issue by adamclasic** [rlmoser99/ruby_exercises#1]
Can you put some comments or more test outputs to explain what does the second method does?

**Comment by rlmoser99** [comment]
Sure, but I'm not sure exactly what is method #2. Are you referring to the 2nd bubble_sort_by or a different file? Let me know the file name & the code line number  - then I'll do what I can to explain.

**Comment by adamclasic** [comment]
the 2nd bubble_sort_by.

**Comment by rlmoser99** [comment]
Ok, I've updated it. I hope that it makes more sense. If not, please let me know the line of code that you are stuck on and I'll do my best to explain it further.

**Comment by adamclasic** [comment]
Thank you verry clear.
